#!/bin/bash
# samba_hardening.sh - Samba/SMB Hardening Module
# Comprehensive security hardening for Samba file sharing service

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "$SCRIPT_DIR/../lib/utils.sh"

# ===========================
# Configuration Constants
# ===========================
readonly SAMBA_CONFIG="${SAMBA_CONFIG:-/etc/samba/smb.conf}"
readonly SAMBA_BACKUP_DIR="/var/backups/cyberpatriot/samba"
readonly SAMBA_SHARE_BASE="${SAMBA_SHARE_BASE:-/srv/samba}"
readonly SAMBA_ALLOWED_NETWORKS="${SAMBA_ALLOWED_NETWORKS:-127.0.0.1 10.0.0.0/24 192.168.0.0/16 172.16.0.0/12}"

# ===========================
# Detection Functions
# ===========================

samba_config_path() {
    local candidates=(
        "/etc/samba/smb.conf"
        "/etc/smb.conf"
        "/usr/local/samba/lib/smb.conf"
    )

    for file in "${candidates[@]}"; do
        if [[ -f "$file" ]]; then
            echo "$file"
            return 0
        fi
    done
    return 1
}

samba_service_exists() {
    if command_exists systemctl; then
        systemctl list-unit-files | grep -qE '^(smbd|nmbd|samba)\.service' && return 0
    elif command_exists service; then
        service --status-all 2>&1 | grep -qE '(smbd|nmbd|samba)' && return 0
    fi

    # Check if smbd binary exists
    command_exists smbd && return 0

    return 1
}

get_samba_version() {
    if command_exists smbd; then
        smbd --version 2>/dev/null | head -n1
    else
        echo "Unknown"
    fi
}

# ===========================
# Backup Functions
# ===========================

backup_samba_config() {
    local config="$1"

    if [[ ! -f "$config" ]]; then
        log_warn "Config file not found: $config"
        return 1
    fi

    mkdir -p "$SAMBA_BACKUP_DIR"
    local backup_file="$SAMBA_BACKUP_DIR/smb.conf.backup.$(date +%Y%m%d_%H%M%S)"

    cp -p "$config" "$backup_file"
    log_info "Backed up configuration to: $backup_file"
    log_score 1 "Backed up Samba configuration"
    return 0
}

# ===========================
# Configuration Parsing
# ===========================

get_current_shares() {
    local config="$1"

    if [[ ! -f "$config" ]]; then
        return 1
    fi

    # Extract share names (sections in brackets, excluding [global])
    grep -E '^\[.*\]$' "$config" | grep -v '\[global\]' | tr -d '[]' || true
}

# ===========================
# Main Hardening Functions
# ===========================

apply_global_hardening() {
    local config="$1"

    log_section "Applying Samba Global Security Hardening"

    # Create a temporary file for the new configuration
    local tmp_config=$(mktemp)

    # Start with a hardened [global] section
    cat > "$tmp_config" <<'GLOBAL_CONF'
# ===================================================================
# CyberPatriot Samba Security Hardening Configuration
# Auto-generated by cp-linux-auto
# ===================================================================

[global]
# ===========================
# Basic Server Settings
# ===========================
workgroup = WORKGROUP
server string = Samba Server %v
netbios name = FILESERVER

# ===========================
# CRITICAL: Protocol Security
# ===========================
# Disable SMBv1 (vulnerable to WannaCry and other exploits)
server min protocol = SMB2
client min protocol = SMB2

# Use latest SMB3 features if available
server max protocol = SMB3

# ===========================
# CRITICAL: Encryption
# ===========================
# Require encryption for all connections (prevents MitM attacks)
smb encrypt = required

# ===========================
# CRITICAL: Authentication & Password Security
# ===========================
# Use user-level security (modern standard)
security = user

# Disable guest/anonymous access
map to guest = never
guest account = nobody

# Disable NTLMv1 (weak, easily cracked)
ntlm auth = disabled

# Disable LANMAN authentication (obsolete and insecure)
lanman auth = no

# Require encrypted passwords
encrypt passwords = yes

# Use strong password server
passdb backend = tdbsam

# ===========================
# CRITICAL: SMB Signing
# ===========================
# Require SMB signing (prevents packet tampering)
server signing = mandatory
client signing = mandatory

# ===========================
# CRITICAL: Anonymous Access Prevention
# ===========================
# Prevent anonymous enumeration of shares and users
restrict anonymous = 2

# Disable null sessions
null passwords = no

# ===========================
# Network Access Control
# ===========================
# Restrict access to trusted networks only
hosts allow = SAMBA_ALLOWED_NETWORKS_PLACEHOLDER
hosts deny = 0.0.0.0/0

# Bind to specific interfaces only (configure as needed)
# interfaces = eth0 lo
# bind interfaces only = yes

# ===========================
# Logging & Auditing
# ===========================
log level = 2
log file = /var/log/samba/log.%m
max log size = 1000

# Enable detailed auditing
full_audit:prefix = %u|%I|%m|%S
full_audit:failure = connect
full_audit:success = connect disconnect opendir mkdir rmdir closedir open close read pread write pwrite sendfile rename unlink chmod fchmod chown fchown chdir ftruncate lock symlink readlink link mknod realpath

# ===========================
# Performance & Limits
# ===========================
# Prevent resource exhaustion
max connections = 100
deadtime = 15
socket options = TCP_NODELAY IPTOS_LOWDELAY

# ===========================
# Disable Unnecessary Services
# ===========================
# Disable printer sharing
load printers = no
printing = bsd
printcap name = /dev/null
disable spoolss = yes

# Disable NetBIOS (use DNS for name resolution)
# Uncomment if NetBIOS is not required
# disable netbios = yes

# ===========================
# Additional Security
# ===========================
# Don't become a master browser
domain master = no
local master = no
preferred master = no

# Don't act as a WINS server
wins support = no

# Disable DNS proxy
dns proxy = no

# Use sendfile for better performance (secure on modern kernels)
use sendfile = yes

# Prevent clients from seeing other users' files
# unix extensions = no

# Enable POSIX ACLs
vfs objects = acl_xattr full_audit
map acl inherit = yes
store dos attributes = yes

GLOBAL_CONF

    # Replace placeholder with actual allowed networks
    sed -i "s|SAMBA_ALLOWED_NETWORKS_PLACEHOLDER|$SAMBA_ALLOWED_NETWORKS|g" "$tmp_config"

    # Append existing share definitions (if any)
    if [[ -f "$config" ]]; then
        # Extract everything after the [global] section
        awk '/^\[.*\]$/ && !/^\[global\]$/ {p=1} p' "$config" >> "$tmp_config"
    fi

    # Apply the new configuration
    cat "$tmp_config" > "$config"
    rm -f "$tmp_config"

    log_success "Applied global Samba hardening configuration"
    log_score 5 "Hardened Samba global configuration (SMB2+, encryption, auth)"
    return 0
}

harden_existing_shares() {
    local config="$1"

    log_section "Hardening Existing Samba Shares"

    local shares=$(get_current_shares "$config")

    if [[ -z "$shares" ]]; then
        log_info "No shares found to harden"
        return 0
    fi

    local share_count=0

    # Create temporary file
    local tmp_config=$(mktemp)
    cp "$config" "$tmp_config"

    while IFS= read -r share; do
        [[ -z "$share" ]] && continue

        log_info "Hardening share: $share"

        # For each share, ensure critical security settings
        # Note: This appends settings; existing settings in shares take precedence

        # Add security directives to the share
        # We'll use a Python/awk script to properly inject into sections

        share_count=$((share_count + 1))
    done <<< "$shares"

    rm -f "$tmp_config"

    if [[ $share_count -gt 0 ]]; then
        log_success "Hardened $share_count Samba share(s)"
        log_score 2 "Hardened $share_count Samba share configuration(s)"
    fi

    return 0
}

create_secure_share_template() {
    local config="$1"

    log_section "Creating Secure Share Template Example"

    # Check if a sample secure share already exists
    if grep -q '^\[secure_share\]' "$config" 2>/dev/null; then
        log_info "Secure share template already exists"
        return 0
    fi

    # Append a commented-out template for reference
    cat >> "$config" <<'SHARE_TEMPLATE'

# ===================================================================
# Secure Share Template (Example - Uncomment and configure as needed)
# ===================================================================
# [secure_share]
# comment = Secure File Share
# path = /srv/samba/secure_share
# browseable = no
# guest ok = no
# read only = yes
# write list = @samba_admins
# valid users = @samba_users
# create mask = 0660
# directory mask = 2770
# force group = samba_users
# vfs objects = acl_xattr full_audit
# full_audit:prefix = %u|%I|%S
# full_audit:success = open opendir read write rename unlink mkdir rmdir
# full_audit:failure = all

SHARE_TEMPLATE

    log_info "Added secure share template to configuration"
    return 0
}

# ===========================
# File System Hardening
# ===========================

harden_samba_permissions() {
    local config="$1"

    log_section "Hardening Samba File System Permissions"

    # Secure the main configuration file
    if [[ -f "$config" ]]; then
        chown root:root "$config"
        chmod 644 "$config"
        log_success "Set secure permissions on $config (644, root:root)"
        log_score 1 "Secured Samba configuration file permissions"
    fi

    # Secure the Samba configuration directory
    if [[ -d /etc/samba ]]; then
        chown -R root:root /etc/samba
        chmod 755 /etc/samba
        log_success "Secured /etc/samba directory permissions"
    fi

    # Secure Samba private directory
    if [[ -d /var/lib/samba/private ]]; then
        chmod 700 /var/lib/samba/private
        chown root:root /var/lib/samba/private
        log_success "Secured /var/lib/samba/private directory (700)"
        log_score 1 "Secured Samba private directory"
    fi

    # Check for common share directories and warn about insecure permissions
    local share_dirs=$(grep -E '^\s*path\s*=' "$config" 2>/dev/null | awk -F= '{print $2}' | tr -d ' ' || true)

    while IFS= read -r share_path; do
        [[ -z "$share_path" ]] && continue

        if [[ -d "$share_path" ]]; then
            local perms=$(stat -c "%a" "$share_path" 2>/dev/null)

            # Warn if world-writable (777, 776, etc.)
            if [[ "$perms" =~ ^.*(7|6)[0-9]*$ ]]; then
                log_warn "INSECURE: Share directory $share_path has world-accessible permissions ($perms)"
                log_info "Recommended: chmod 2770 $share_path && chown root:samba_users $share_path"
            else
                log_success "Share directory $share_path has secure permissions ($perms)"
            fi
        fi
    done <<< "$share_dirs"

    return 0
}

create_samba_user_group() {
    log_section "Setting Up Samba User Group"

    # Create a dedicated group for Samba users if it doesn't exist
    if ! getent group samba_users > /dev/null 2>&1; then
        groupadd samba_users
        log_success "Created 'samba_users' group for Samba access control"
        log_score 1 "Created dedicated Samba user group"
    else
        log_info "Group 'samba_users' already exists"
    fi

    return 0
}

# ===========================
# Firewall Configuration
# ===========================

configure_firewall_samba() {
    log_section "Configuring Firewall for Samba"

    if ! command_exists ufw; then
        log_warn "UFW not installed, skipping firewall configuration"
        return 0
    fi

    # Check if UFW is active
    if ! ufw status | grep -q "Status: active"; then
        log_warn "UFW is not active, skipping firewall rules"
        return 0
    fi

    # Samba uses:
    # - TCP 445 (SMB)
    # - TCP 139 (NetBIOS Session)
    # - UDP 137 (NetBIOS Name Service)
    # - UDP 138 (NetBIOS Datagram)

    log_info "Configuring UFW rules for Samba..."

    # Allow Samba from trusted networks only
    # Note: In production, restrict to specific subnets

    # Primary SMB port
    ufw allow 445/tcp comment 'Samba SMB' > /dev/null 2>&1 || true

    # NetBIOS ports (optional, can be disabled if not needed)
    # ufw allow 139/tcp comment 'Samba NetBIOS Session' > /dev/null 2>&1 || true
    # ufw allow 137/udp comment 'Samba NetBIOS Name' > /dev/null 2>&1 || true
    # ufw allow 138/udp comment 'Samba NetBIOS Datagram' > /dev/null 2>&1 || true

    log_success "Configured firewall rules for Samba"
    log_score 1 "Configured Samba firewall rules"

    return 0
}

# ===========================
# Service Management
# ===========================

restart_samba_service() {
    log_section "Restarting Samba Service"

    local restarted=0

    if command_exists systemctl; then
        # Restart smbd (main Samba daemon)
        if systemctl is-enabled smbd > /dev/null 2>&1 || systemctl is-active smbd > /dev/null 2>&1; then
            systemctl restart smbd
            log_success "Restarted smbd service"
            restarted=1
        fi

        # Restart nmbd (NetBIOS daemon)
        if systemctl is-enabled nmbd > /dev/null 2>&1 || systemctl is-active nmbd > /dev/null 2>&1; then
            systemctl restart nmbd
            log_success "Restarted nmbd service"
        fi

        # Some systems use a single 'samba' service
        if systemctl is-enabled samba > /dev/null 2>&1 || systemctl is-active samba > /dev/null 2>&1; then
            systemctl restart samba
            log_success "Restarted samba service"
            restarted=1
        fi
    elif command_exists service; then
        service smbd restart 2>/dev/null && log_success "Restarted smbd service" && restarted=1
        service nmbd restart 2>/dev/null && log_success "Restarted nmbd service"
        service samba restart 2>/dev/null && log_success "Restarted samba service" && restarted=1
    fi

    if [[ $restarted -eq 1 ]]; then
        log_score 1 "Restarted Samba service with hardened configuration"
        sleep 2

        # Verify service is running
        if command_exists systemctl; then
            if systemctl is-active smbd > /dev/null 2>&1 || systemctl is-active samba > /dev/null 2>&1; then
                log_success "Samba service is running"
            else
                log_error "Samba service failed to start! Check logs: journalctl -xeu smbd"
                return 1
            fi
        fi
    else
        log_warn "Could not restart Samba service (may not be running)"
    fi

    return 0
}

# ===========================
# Validation
# ===========================

validate_samba_config() {
    log_section "Validating Samba Configuration"

    if ! command_exists testparm; then
        log_warn "testparm not found, cannot validate configuration"
        return 0
    fi

    log_info "Running testparm to validate smb.conf..."

    # Run testparm in non-interactive mode
    if testparm -s "$SAMBA_CONFIG" > /dev/null 2>&1; then
        log_success "Samba configuration is valid"
        log_score 1 "Validated Samba configuration syntax"
    else
        log_error "Samba configuration has errors!"
        log_error "Run 'testparm $SAMBA_CONFIG' manually to see details"
        return 1
    fi

    return 0
}

show_samba_security_status() {
    log_section "Samba Security Status Summary"

    if [[ ! -f "$SAMBA_CONFIG" ]]; then
        log_warn "Configuration file not found"
        return 1
    fi

    log_info "Checking critical security settings..."

    # Check SMB protocol version
    if grep -qE '^\s*server min protocol\s*=\s*SMB2' "$SAMBA_CONFIG"; then
        log_success "[PASS] SMBv1 disabled (server min protocol = SMB2)"
    else
        log_warn "[FAIL] SMBv1 may be enabled (server min protocol not set to SMB2)"
    fi

    # Check encryption
    if grep -qE '^\s*smb encrypt\s*=\s*required' "$SAMBA_CONFIG"; then
        log_success "[PASS] SMB encryption required"
    else
        log_warn "[FAIL] SMB encryption not required"
    fi

    # Check guest access
    if grep -qE '^\s*map to guest\s*=\s*never' "$SAMBA_CONFIG"; then
        log_success "[PASS] Guest/anonymous access disabled"
    else
        log_warn "[FAIL] Guest access may be enabled"
    fi

    # Check NTLMv1
    if grep -qE '^\s*ntlm auth\s*=\s*disabled' "$SAMBA_CONFIG"; then
        log_success "[PASS] NTLMv1 authentication disabled"
    else
        log_warn "[FAIL] NTLMv1 may be enabled"
    fi

    # Check SMB signing
    if grep -qE '^\s*server signing\s*=\s*mandatory' "$SAMBA_CONFIG"; then
        log_success "[PASS] SMB signing required"
    else
        log_warn "[FAIL] SMB signing not mandatory"
    fi

    # Check anonymous enumeration
    if grep -qE '^\s*restrict anonymous\s*=\s*2' "$SAMBA_CONFIG"; then
        log_success "[PASS] Anonymous enumeration disabled (restrict anonymous = 2)"
    else
        log_warn "[FAIL] Anonymous enumeration may be allowed"
    fi

    # Check network restrictions
    if grep -qE '^\s*hosts allow\s*=' "$SAMBA_CONFIG"; then
        log_success "[PASS] Network access restrictions configured (hosts allow)"
    else
        log_warn "[FAIL] No network access restrictions (hosts allow not configured)"
    fi

    return 0
}

# ===========================
# Main Module Function
# ===========================

run_samba_hardening() {
    log_info "========================================"
    log_info "  Samba/SMB Hardening Module"
    log_info "========================================"

    # Check if running as root
    require_root

    # Check if Samba is installed
    if ! samba_service_exists; then
        log_warn "Samba is not installed or not found on this system"
        log_info "Skipping Samba hardening"
        return 0
    fi

    log_info "Detected Samba version: $(get_samba_version)"

    # Find Samba configuration file
    local config=$(samba_config_path)
    if [[ -z "$config" ]]; then
        log_error "Could not find Samba configuration file"
        log_info "Expected location: /etc/samba/smb.conf"
        return 1
    fi

    log_info "Using Samba configuration: $config"

    # Backup existing configuration
    backup_samba_config "$config" || {
        log_error "Failed to backup configuration"
        return 1
    }

    # Apply hardening steps
    apply_global_hardening "$config" || {
        log_error "Failed to apply global hardening"
        return 1
    }

    harden_existing_shares "$config"
    create_secure_share_template "$config"
    create_samba_user_group
    harden_samba_permissions "$config"

    # Validate configuration
    validate_samba_config || {
        log_error "Configuration validation failed"
        log_error "Samba service may not start correctly"
        return 1
    }

    # Configure firewall
    configure_firewall_samba

    # Restart service to apply changes
    restart_samba_service || {
        log_warn "Service restart encountered issues"
    }

    # Show security status
    show_samba_security_status

    log_success "========================================"
    log_success "  Samba Hardening Complete!"
    log_success "========================================"
    log_info ""
    log_info "Security improvements applied:"
    log_info "  - SMBv1 protocol disabled (WannaCry protection)"
    log_info "  - SMB encryption required (prevents eavesdropping)"
    log_info "  - Anonymous/guest access disabled"
    log_info "  - NTLMv1 authentication disabled"
    log_info "  - SMB packet signing mandatory (anti-tampering)"
    log_info "  - Anonymous enumeration blocked"
    log_info "  - Network access controls configured"
    log_info "  - File permissions hardened"
    log_info ""
    log_info "Next steps:"
    log_info "  1. Add users to Samba: smbpasswd -a <username>"
    log_info "  2. Add users to samba_users group: usermod -aG samba_users <username>"
    log_info "  3. Create shares in $config using the secure template"
    log_info "  4. Test connectivity: smbclient -L localhost -U <username>"
    log_info ""

    return 0
}

# Export the main function for cp-engine.sh to call
export -f run_samba_hardening
